### ISSUE TITLE
type 'List<Object>' is not a subtype of type 'List<(Store<AppState>, dynamic, (dynamic) => void) => void>'

### ISSUE THREAD

**Issue by jaggerwang** [brianegan/redux_logging#7]
## Error

```
Launching lib/main.dart on iPhone X in debug mode...
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'List<Object>' is not a subtype of type 'List<(Store<AppState>, dynamic, (dynamic) => void) => void>'
#0      new TangboleApp (file:///Users/jagger/projects/tangbole/app/lib/main.dart:36:79)
#1      main (file:///Users/jagger/projects/tangbole/app/lib/main.dart:18:10)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

## Code

```dart
...

    final persistor = Persistor<AppState>(
      storage: FlutterStorage('tangbole'),
      decoder: AppState.fromJson,
      version: 10000,
      migrations: {},
    );

    var mws = [persistor.createMiddleware()];
    mws.addAll(createMiddlewares());
    mws.add(LoggingMiddleware.printer());

    final store = Store<AppState>(
      appReducer,
      initialState: AppState(),
      middleware: mws,
    );

    persistor.load(store);

...
```

## Env

```yaml
name: tangbole
description: A tumblr client app.

dependencies:
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.1
  http: ^0.11.3+16
  meta: ^1.1.5
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_persist: ^0.7.0-rc.2
  redux_persist_flutter: ^0.6.0-rc.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

```
